title: Alex Socop
description: |
  <p>Myron Alexander Socop Arango（舒冠宇）</p>

  <p>Xelajuj No'j (Quetzaltenango), Guatemala, 1988. Indigenous K’iche’ Maya scholar and writer. His literary work has been published in diverse magazines and collections. The most recent one is Punto de partida 190 (UNAM, 2015). He published Temblores del silencio (Metáfora editores, 2012) and Poemas sueltos (90 plaquettes, 2014). He has participated in poetry festivals in Central America and Mexico, and he was part of the organizing committee for the Quetzaltenango International Poetry Festival from 2011 to 2019.</p>

  <p>In 2021, he received the MOFA scholarship to pursue doctoral studies at National Taiwan Normal University. In 2024, the Cognitive Science Society awarded him the prize for the Initiative in Dissemination and Participation in Cognitive Sciences for the project <em>The Cognitive Science Behind the Adventures of Junajpu and Xbalamke: Spreading Awareness of Cognitive Science Among Educators in Mayan and Mestizo Communities</em>.</p>

  <p>His academic and professional interests broadly include shared book reading and brain development, EMI, multicultural and global education, and environmental humanities.</p>

show_downloads: false
theme: jekyll-theme-minimal
